sudo: false
language: node_js
before_install:
  - npm install npm -g
node_js:
  - "0.10"
  - "0.12"
  - "io.js"
  - "4"
  - "5"
  - "6"
matrix:
  include:
    - node_js: "4"
      env: TEST_SUITE=standard
env:
  - TEST_SUITE=coverage
  - TEST_SUITE=integration
  - TEST_SUITE=unit
script: npm run-script $TEST_SUITE
